feat: Dynamic config support
canonical/pycloudlib pull request #214
Opened 2022-08-30 16:53 UTC by mjd-x

Removes the requirement for pycloudlib and OCI config files to be in a
fixed path so pycloudlib can operate as a library. This allows specifying
parameters for the clouds independently of the config files, facilitating
integration with automated pipelines.

2022-08-31 11:32 UTC, aciba90 requested changes
Thanks, @mjd-x, for this improvement.

I have left you a comment explaining why I think we must still try to read the config from the default locations.

2022-08-31 11:32 UTC, aciba90 commented on pycloudlib/cloud.py
> +            self.config = {}
If `config_file == None` in `BaseCloud.__init__`, we are not trying to read the config from the default locations [CONFIG_PATHS](https://github.com/canonical/pycloudlib/blob/main/pycloudlib/config.py#L11). So, if we try to instantiate an OCI class with or without the new `config_dict` and we have a valid pycloudlib `config` in a default location, we get the following exception:

```python
>>> from pycloudlib import oci
>>> oci.cloud.OCI("test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aciba/canonical/pycloudlib/pycloudlib/oci/cloud.py", line 56, in __init__
    availability_domain or self.config["availability_domain"]
KeyError: 'availability_domain'
```

This is also true for other clouds as, this happens in the base class initialization of every cloud.

I think we have to try to read the config in the default locations for other clouds than `OCI` and for `OCI` if `availability_domain`, `compartment_id` or `config_dict` are not given at initialization time.

2022-09-02 09:42 UTC, aciba90 approved these changes
LGTM. Thanks, @mjd-x!

2022-09-12 20:10 UTC, blackboxsw approved these changes
LGTM as is. I think we have the machinery and the copy of the proposed cloud-init 22.3.3 in a separate PPA to keep iterating on making sure Azure's PPS environment better raises errors, and this existing functionality fixes the immediate upgrade issue and closed gaps in integration and unittesting to ensure we don't get down this path without a failure signal in the future on Azure.

2022-09-14 16:56 UTC, mjd-x commented
Had a quick chat with @TheRealFalcon where we decided to keep these changes over modifying `parse_config` to log instead of raise, since the config file exception makes the situation clearer for the user than getting a `KeyError` or something similar later on.

2022-09-14 18:58 UTC, TheRealFalcon approved these changes
Thanks for the update and the explanation!

2022-09-14 18:58 UTC, merged