Oracle allow explicitly specifying vcn for subnet selection
canonical/pycloudlib pull request #315
Opened 2023-08-09 12:26 UTC by a-dubs

2023-08-16 07:19 UTC, CalvoM reviewed
LGTM, but I need to do some testing for the functionality.

2023-08-16 21:07 UTC, holmanb commented on pycloudlib/oci/utils.py
> +        target_subnet_name: Name of the subnet to look for.
Is this line needed?

2023-08-18 08:21 UTC, CalvoM approved these changes
Tested it with CTF and it works. LGTM.

2023-08-24 11:54 UTC, aciba90 requested changes
Thanks! Apart from the typing fix, LGTM.

2023-08-24 11:54 UTC, aciba90 commented on pycloudlib/oci/utils.py
> +    vcn_name: str = None,
```suggestion
    vcn_name: Optional[str] = None,
```

And the appropriate import if required.

2023-08-24 15:47 UTC, a-dubs commented on pycloudlib/oci/utils.py
> +    vcn_name: str = None,
Fixed, tysm :D

2023-08-24 16:56 UTC, merged

2023-08-24 17:49 UTC, a-dubs commented
Jira ticket for context: https://warthogs.atlassian.net/browse/CPC-2908