feat(azure): attach nics to running instance (SC-1712)
canonical/pycloudlib pull request #340
Opened 2024-02-09 14:42 UTC by CalvoM

2024-03-06 18:22 UTC, AleksaSvitlica commented
Should this MP implement `add_network_interface` and `remove_network_interface` since they are defined in BaseInstance? That seems like it might better align with the rest of pycloudlib.

2024-03-07 09:11 UTC, CalvoM commented
Oh, I had totally overlooked that. Let me dive deeper into that and make necessary changes.

2024-03-07 11:05 UTC, aciba90 requested changes
Thanks, @CalvoM!

> Should this MP implement add_network_interface and remove_network_interface since they are defined in BaseInstance? That seems like it might better align with the rest of pycloudlib.

As @AleksaSvitlica said, I think we should adhere to / extend the  `add_network_interface` and `remove_network_interface` interfaces of `BaseInstance`.

2024-03-07 11:05 UTC, aciba90 commented on VERSION
> +1!6.0.4
Bump minor as we are introducing new features.

2024-03-07 13:42 UTC, CalvoM commented on pycloudlib/azure/instance.py
> +                "VM must be deallocated before attaching NIC"
I have reviewed this and it does not need to be deallocated but just stopped.

2024-03-08 10:33 UTC, CalvoM commented on pycloudlib/azure/instance.py
> +                "VM must be deallocated before attaching NIC"
After testing, we need to deallocate to add/remove nics.

2024-03-12 19:31 UTC, aciba90 approved these changes
LGTM, thanks!

2024-03-12 19:32 UTC, merged