Prevent incorrect version bumps
canonical/pycloudlib pull request #354
Opened 2024-03-25 22:31 UTC by a-dubs

Improved the github CI/CD version check so that it not only ensures the version has been bumped, but that the version bump is sane. 

The following tests were run against the version check to ensure it functions as desired:
```python
class TestVersionComparison(unittest.TestCase):
    def test_pass_cases(self):
        self.assertEqual(compare_versions("1!1.0.0", "1!1.0.1"), "Version bump is sane.")
        self.assertEqual(compare_versions("1!1.0.0", "1!1.1.0"), "Version bump is sane.")
        self.assertEqual(compare_versions("1!1.1.1", "1!2.0.0"), "Version bump is sane.")
        self.assertEqual(compare_versions("1!1.1.0", "1!1.1.1"), "Version bump is sane.")
        self.assertEqual(compare_versions("1!1.1.1", "1!1.1.2"), "Version bump is sane.")

    def test_fail_cases(self):
        self.assertNotEqual(compare_versions("1!1.0.0", "1!1.0.0"), "Version bump is sane.")
        self.assertNotEqual(compare_versions("1!1.0.0", "1!1.2.1"), "Version bump is sane.")
        self.assertNotEqual(compare_versions("1!1.0.0", "1!2.1.0"), "Version bump is sane.")
        self.assertNotEqual(compare_versions("1!1.0.0", "1!0.9.9"), "Version bump is sane.")
        self.assertNotEqual(compare_versions("1!1.1.2", "1!1.1.1"), "Version bump is sane.")
        self.assertNotEqual(compare_versions("1!1.2.1", "1!1.1.1"), "Version bump is sane.")
        self.assertNotEqual(compare_versions("1!2.1.1", "1!1.1.1"), "Version bump is sane.")
```

2024-03-26 16:24 UTC, a-dubs commented on VERSION
> +1!6.2.3
```suggestion
1!6.2.4
```

2024-04-04 14:07 UTC, blackboxsw reviewed
Generally looks good.
Minimally the following should be resolved:
- I'd change the success message to include Valid version instead of what we have.
- isort and black formatting issues with the added scrip

Optionally:
- You could consider using packaging.version for this comparison for readability, but it's your call as it's about the same amount of code.

2024-04-04 14:07 UTC, blackboxsw commented on .github/workflows/version_check.py
> +    if result != "Version bump is sane.":
Generic inclusive language nit.
```suggestion
    if not result.startswith("Valid version"):
```

2024-04-04 15:34 UTC, holmanb requested changes

2024-04-04 15:34 UTC, holmanb commented on .github/workflows/version_check.py
> +        return "Only one digit can be incremented at a time.
invalid python, missing double quote

2024-04-04 15:36 UTC, a-dubs commented on .github/workflows/version_check.py
> +        return "Only one digit can be incremented at a time.
```suggestion
        return "Only one digit can be incremented at a time."
```

2024-04-24 15:12 UTC, a-dubs commented
dear god, whoever merges this, please squash this heretical commit history :skull: :skull: :skull:

2024-04-24 15:31 UTC, blackboxsw commented
> dear god, whoever merges this, please squash this blasphemous commit history 💀 💀 💀

@a-dubs you can squash merge at will :)
```
git reset --sort HEAD~10
git commit # add your desired commit message
```

2024-04-24 15:58 UTC, holmanb approved these changes
thanks @a-dubs!

2024-04-24 15:59 UTC, merged