feat(ec2): Allow using ec2 profile as creds
canonical/pycloudlib pull request #412
Opened 2024-09-10 15:16 UTC by TheRealFalcon

I have a feeling I'm just missing something obvious, but with my SSO creds I can no longer get a secret key, but using a profile is an alternative that should work too.

2024-09-10 16:49 UTC, a-dubs approved these changes

2024-09-11 07:33 UTC, aciba90 commented
> I have a feeling I'm just missing something obvious, but with my SSO creds I can no longer get a secret key, but using a profile is an alternative that should work too.

I think the idea behind SSO access is:

SSO let you access your root AWS account. From the root account, one can create a non-root user. And those non-root user's credentials can be used as previously in pycloudlib.

Does that work for you?

2024-09-11 16:14 UTC, TheRealFalcon commented
> Does that work for you?

Makes sense, but I was actually able to find the credentials. They're just listed on a different screen at login time rather than the original account page.

I think this functionality is still useful though as it obviates the need to manage secret keys.

2024-09-12 13:48 UTC, aciba90 requested changes
Changeset looks good to me, thanks.

I think we should extend https://github.com/canonical/pycloudlib/blob/main/docs/clouds/ec2.md to clarify on how to use the `profile` mode. WDYT?

2024-09-12 13:48 UTC, aciba90 commented on pycloudlib.toml.template
> +# With modern SSO, these should no longer be necessary.
Nit: `With modern SSO` sounds a bit pretentious and likely prone to age bad. Something like the following?

```suggestion
# If profile is given, these are not necessary.
```

2024-10-22 13:16 UTC, aciba90 approved these changes
LGTM

2024-10-22 13:27 UTC, merged