Run lxc commands as non root by default
canonical/pycloudlib pull request #56
Opened 2020-11-18 20:22 UTC by lucasmoura

In ubuntu-advantage-tools, we require some LXD commands to be run as `non-root`. This PR changes the default behavior of LXD to run exec commands as non-root.

This will impact some `cloud-init` tests, but we already have a [PR](https://github.com/canonical/cloud-init/pull/676) to handle that

2020-11-18 22:01 UTC, TheRealFalcon commented
Actually...lxd is the exception for us as all other clouds already execute non-root. This may actually simplify things for us :slightly_smiling_face:

2020-11-19 20:05 UTC, TheRealFalcon approved these changes
Travis is failing as this will break cloud-init tests, but once https://github.com/canonical/cloud-init/pull/664 lands it should be a one-line fix. Since we've pinned our pycloudlib version, I'm not concerned these failures.

2020-11-26 04:20 UTC, blackboxsw approved these changes
Once https://github.com/canonical/cloud-init/pull/694 lands, this looks good to land

2020-11-26 15:42 UTC, OddBloke approved these changes
The conclusion we came to in https://github.com/canonical/cloud-init/pull/664 was that `pycloudlib` should consistently execute commands as an unprivileged user by default. This aligns LXD with the other clouds in pycloudlib which use SSH.

2020-11-26 17:31 UTC, OddBloke requested changes
Per https://github.com/canonical/cloud-init/pull/694#discussion_r531159622, running commands as UID 1000 is _not_ the same as running commands as `self.username`. I believe this will need modification to look up the UID of `self.username` before running `lxc exec` for the first time.

2020-11-26 19:49 UTC, lucasmoura commented
@OddBloke I have updated the code to get the `user id`  before running any `lxc exec` commands.

The solution I have is to retry the `id -u` command until the user was created. With that solution, I think we can drop from LXD the call for [_wait_for_execute](https://github.com/canonical/pycloudlib/blob/master/pycloudlib/instance.py#L369), since the `user_id` property is kind of covering that already

2020-11-26 21:14 UTC, OddBloke commented on pycloudlib/lxd/instance.py
> +        self._user_id = None
```suggestion
```

2020-11-26 21:14 UTC, OddBloke approved these changes
Thanks!

2020-11-26 22:16 UTC, merged